### ISSUE TITLE
Power led

### ISSUE THREAD

**Issue by thirax** [Wquarks/LoRa#1]
faire en sorte que la led tan du vert au rouge en fonction de la puissance 
rssi faisant référance au bruit != de la puissance 

et on utilise ton code couleur pour le debugage du style if(gps.getcoord() = null) allor affichage bleux idem pour quand pas de signal

**Comment by Wquarks** [comment]
je ne pense pas que ce soit utile : ca sera seulement pratique pour voir sur le terrain, mais ca ne nous permettra pas d'analyser les data

**Comment by thirax** [comment]
Mais Mais ... La feignantise
oui ces pratique sur le terrain ces justement pour ça que je propose l'ajout
